apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: mutating-example.iceyao.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/mutating"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", "extensions", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["deployments","services", "ingresses"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled

