apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: mutating-example.iceyao.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/mutating"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVSzQrVndlTFpnUEZuSUJHWUN4QkF6REoxN3B3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNRMDR4RWpBUUJnTlZCQWdUQ1VkMVlXNW5SRzl1WnpFTE1Ba0dBMVVFQnhNQwpVMW94RERBS0JnTlZCQW9UQTJzNGN6RVBNQTBHQTFVRUN4TUdVM2x6ZEdWdE1STXdFUVlEVlFRREV3cHJkV0psCmNtNWxkR1Z6TUI0WERURTVNREl5TURBMk5ERXdNRm9YRFRJME1ESXhPVEEyTkRFd01Gb3dZakVMTUFrR0ExVUUKQmhNQ1EwNHhFakFRQmdOVkJBZ1RDVWQxWVc1blJHOXVaekVMTUFrR0ExVUVCeE1DVTFveEREQUtCZ05WQkFvVApBMnM0Y3pFUE1BMEdBMVVFQ3hNR1UzbHpkR1Z0TVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXR0aUR3UXlQSzQxZkk4TmdSamRGM0FJcjlQMVUKaEJTMEpGbEVKMlVWRGhRRGZTK25zNDJyNElIR2F5V2F5ZGxkbGNGWDdYaGcwcVFBT05MSysycDZmWG9qQ0RNNgpaRUFSTm5PdVFHRmFPZnJpaHN1a1FzajZabjNWU2k4UGd3Y01KVXpqaVk5MzJjT1RjUU00OUo5TE96MFFDcDhFCnRRK3NvNnFFN0JsMG9tK2lmUnVxMStPNWJHbUNCYjJFRVFmZ0hldWx1WjhMb3lIaFFFYkkzcXE5ZTNYdGR5S20KS08xQlJrN1ovbTI0YW1vQzcyZ3hsaktQMktWMW9pQ1pqK1ZjcEZ3RVBwbVlhTnAxV2Uwams3V2dEWFpVWEJrRQpOcWhDMi9ZMnNVUTVWV20wZE9uQ0E2cEUzRnEyQzdrclZ4aE9lbEtJeEZ6dVY1NkFlQ1Z4ZThxS01RSURBUUFCCm8yWXdaREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBakFkQmdOVkhRNEUKRmdRVVVISXI3UG5uakNPNkdFYzArd2xuN1ByMkhub3dId1lEVlIwakJCZ3dGb0FVVUhJcjdQbm5qQ082R0VjMAord2xuN1ByMkhub3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRXdmKy9DeTYydXZwM0RKSUd1YkZQNEF6S1FMCnBieEp3am4rZHNTSkZKa0l3U0NKSkpQVnd0VThxUGR3QlMyVUtKMWV2RkJ2aysydUx5Q0tXMUY2STVSeWM2NTgKRS9kT1hBUFVQMGNwQTF2d2RrTnY3eUZxQlk5UzdwbTlxMkJaRU9md2JTNXNUa1J6dHdxUDc1REtFZjh0OWVxLwo5Sm5URWhzM3RDVXR2MnVTS0xid0dyVC9sbVB3VDMyWG45MHRZYnJhc2ZyOWJ6UzhxaEFtbDhLbkh5SXMwL0RCCmgrcDVOMGdTUk9ESyt1L0p3U2RubHd3RGlZemVLZm84N1J5cE5DSnQ3VXNYNkozUks4R05Kd1NNeTVzNzBYaFMKMUMwczRSUnNEVDdkaFJzc1BCQ3ZzSDZISGpyTFVBTTdoZDFYQkFka2pNREE0QjhxRG5qYisyZkFLaHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", "extensions", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["deployments","services", "ingresses"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled

