apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-example-svc
  labels:
    app: admission-webhook-example
spec:
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30443
  type: NodePort
  selector:
    app: admission-webhook-example
