apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    app.kubernetes.io/name: sleep
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sleep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sleep
    spec:
      containers:
      - name: sleep
        image: nginx
        imagePullPolicy: IfNotPresent
